# Generated by Django 5.2.1 on 2025-05-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_financeira', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='amont',
            new_name='amount',
        ),
    ]
