# Generated by Django 5.2.1 on 2025-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_financeira', '0002_rename_amont_registros_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='type_register',
            field=models.CharField(default='exit', max_length=100),
        ),
    ]
